baseURL = "https://xinqilin.github.io/"
languageCode = "zh-tw"
DefaultContentLanguage = "zh-tw"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[params]

# Config

title = "Bill.Lin 成長之路"

theme="anatole"

author = "Bill.Lin 成長之路 @"

description = """
後端工程師 Java, Kotlin

成長路上有你有我

很高興認識你 Pleased to meet you!
"""


profilePicture = "images/profile.jpg"

displayMode = "dark"

# disableThemeSwitcher = true

contentratio = 0.78

readMore = true

favicon = "favicons/"

rssFullContent = true

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

enableMediumZoom = false

singleDateFormat = "2006/2/1/"
indexDateFormat = "2006/2/1/"
listDateFormat = "2006/2/1/"

# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 

mainSections = ["post"]



# Navigation bar

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about me"
  url = "/about/"




# Social Media

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/bill-lin-47348017a/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/xinqilin"


[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:zzx123bill@gmail.com"


[[params.socialIcons]]
icon = "fab fa-wordpress-simple"
title = "WordPress"
url = "https://xinqilin.wordpress.com/"


[outputs]
  home = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML"]